# Generated by Django 3.2.25 on 2024-09-06 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('org_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('db_type', models.CharField(choices=[('SQL', 'SQL'), ('NOSQL', 'NoSQL')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MetaTable',
            fields=[
                ('table_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='dynamictable.organization')),
            ],
        ),
        migrations.CreateModel(
            name='MetaColumn',
            fields=[
                ('column_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('data_type', models.CharField(max_length=50)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='dynamictable.metatable')),
            ],
        ),
    ]
